In [1]:
import pandas as pd
import numpy as np

## Institutes

In [2]:
df = pd.read_csv('../outputs/clean/institutes.csv')
df = df.drop_duplicates()
df.head()

,id istituto,nome istituto,tipo istituto,posti regolamentari,posti non disponibili,totale detenuti,polizia penitenziaria - effettivi,polizia penitenziaria - previsti,amministrativi - effettivi,amministrativi - previsti,...,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,dati aggiornati al,personale polizia penitenziaria aggiornato al,personale amministrativo aggiornato al,data di aggiornamento spazi detentivi
0,MII181125,Siracusa,Casa circondariale,545.0,0.0,674.0,227.0,234.0,21.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
1,MII181839,Velletri,Casa circondariale,412.0,26.0,514.0,197.0,275.0,26.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
2,MII181934,Viterbo,Casa circondariale N.C. - Nicandro Izzo,440.0,35.0,694.0,268.0,330.0,29.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
3,MII177384,Lauro,Istituto custodia attenuata per madri,50.0,0.0,7.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,NaN,2024-07-31,NaN
4,MII181115,Siena,Casa circondariale,58.0,0.0,71.0,42.0,41.0,9.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN

### Remove outliers

In [3]:
df.head()

,id istituto,nome istituto,tipo istituto,posti regolamentari,posti non disponibili,totale detenuti,polizia penitenziaria - effettivi,polizia penitenziaria - previsti,amministrativi - effettivi,amministrativi - previsti,...,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,dati aggiornati al,personale polizia penitenziaria aggiornato al,personale amministrativo aggiornato al,data di aggiornamento spazi detentivi
0,MII181125,Siracusa,Casa circondariale,545.0,0.0,674.0,227.0,234.0,21.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
1,MII181839,Velletri,Casa circondariale,412.0,26.0,514.0,197.0,275.0,26.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
2,MII181934,Viterbo,Casa circondariale N.C. - Nicandro Izzo,440.0,35.0,694.0,268.0,330.0,29.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
3,MII177384,Lauro,Istituto custodia attenuata per madri,50.0,0.0,7.0,0.0,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,NaN,2024-07-31,NaN
4,MII181115,Siena,Casa circondariale,58.0,0.0,71.0,42.0,41.0,9.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN

In [4]:
df['dati aggiornati al'] = pd.to_datetime(df['dati aggiornati al'])
df = df.sort_values(by='dati aggiornati al')

In [5]:
# 1. Group by 'dati aggiornati al' and sum 'posti regolamentari'
daily_total_posti = df.groupby('dati aggiornati al')['posti regolamentari'].sum()
daily_total_posti

dati aggiornati al
2024-10-05    51196.0
2024-10-06    51196.0
2024-10-07    51196.0
2024-10-09    51195.0
2024-10-10    51195.0
               ...
2026-05-21    51269.0
2026-05-22    51269.0
2026-05-23    51269.0
2026-05-24    51269.0
2026-05-27    51269.0
Name: posti regolamentari, Length: 476, dtype: float64

In [6]:
# 2. Calculate the percentage difference from the previous day's total
# pct_change() is perfect for this.
daily_total_posti_diff_pct = daily_total_posti.pct_change().abs()
daily_total_posti_diff_pct.tail(20)

dati aggiornati al
2026-05-01    0.000000
2026-05-02    0.000000
2026-05-03    0.000000
2026-05-04    0.000078
2026-05-05    0.000000
2026-05-06    0.000000
2026-05-07    0.000000
2026-05-08    0.000000
2026-05-09    0.000000
2026-05-10    0.000000
2026-05-13    0.000000
2026-05-17    0.000000
2026-05-18    0.000000
2026-05-19    0.000000
2026-05-20    0.000000
2026-05-21    0.000000
2026-05-22    0.000000
2026-05-23    0.000000
2026-05-24    0.000000
2026-05-27    0.000000
Name: posti regolamentari, dtype: float64

In [7]:
# Define the percentage threshold for outlier
percentage_threshold = 0.30

In [8]:
bad_dates = daily_total_posti_diff_pct[daily_total_posti_diff_pct > percentage_threshold].index.tolist()
bad_dates

[]

In [9]:
# Removing false positives
# This assumes the pattern: [True Outlier, False Positive, True Outlier, False Positive, ...]
dates_to_remove = [date for i, date in enumerate(bad_dates) if i % 2 == 0]
dates_to_remove

[]

In [10]:
df_cleaned = df[~df['dati aggiornati al'].isin(dates_to_remove)].copy()
df_cleaned

,id istituto,nome istituto,tipo istituto,posti regolamentari,posti non disponibili,totale detenuti,polizia penitenziaria - effettivi,polizia penitenziaria - previsti,amministrativi - effettivi,amministrativi - previsti,...,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,dati aggiornati al,personale polizia penitenziaria aggiornato al,personale amministrativo aggiornato al,data di aggiornamento spazi detentivi
0,MII181125,Siracusa,Casa circondariale,545.0,0.0,674.0,227.0,234.0,21.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
121,MII179306,Palermo Pagliarelli,Casa circondariale - Antonio Lorusso,1165.0,9.0,1378.0,661.0,581.0,45.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
122,MII176375,Foggia,Casa circondariale,364.0,19.0,710.0,237.0,244.0,31.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
123,MII182919,Pisa,Casa circondariale,197.0,17.0,284.0,191.0,184.0,19.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
124,MII180424,Rovigo,Casa circondariale,211.0,8.0,238.0,128.0,175.0,13.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-05,2024-07-31,2024-07-31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90268,MII179981,Ravenna,Casa circondariale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
90269,MII179364,Parma,Casa di reclusione,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
90270,MII176403,Forlì,Casa circondariale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
90271,MII178638,Modena,Casa circondariale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
90272,MII181125,Siracusa,Casa circondariale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [11]:
df_cleaned.to_csv('../outputs/clean/institutes.csv', index=False, encoding='UTF-8-sig')
df = pd.read_csv('../outputs/clean/institutes.csv')

## Most recent data

In [12]:
# Get the most recent update
df['dati aggiornati al'] = pd.to_datetime(df['dati aggiornati al'], format='%Y-%m-%d')
df_most_recent = df.loc[df.groupby('id istituto')['dati aggiornati al'].idxmax()]

# Adding columns for places available and overcrowding index
df_most_recent['posti disponibili'] = df_most_recent['posti regolamentari'] - df_most_recent['posti non disponibili']
df_most_recent['tasso di affollamento'] = round(((df_most_recent['totale detenuti'] / df_most_recent['posti disponibili'])*100),0)

In [13]:
df_most_recent.value_counts(['dati aggiornati al'])

dati aggiornati al
2026-05-27            190
Name: count, dtype: int64

In [14]:
df_most_recent.columns

Index(['id istituto', 'nome istituto', 'tipo istituto', 'posti regolamentari',
       'posti non disponibili', 'totale detenuti',
       'polizia penitenziaria - effettivi', 'polizia penitenziaria - previsti',
       'amministrativi - effettivi', 'amministrativi - previsti',
       'educatori - effettivi', 'educatori - previsti', 'numero complessivo',
       'numero non disponibili', 'doccia', 'bidet', 'portatori di handicap',
       'servizi igienici con porta', 'accensione luce autonoma',
       'prese elettriche', 'dati aggiornati al',
       'personale polizia penitenziaria aggiornato al',
       'personale amministrativo aggiornato al',
       'data di aggiornamento spazi detentivi', 'posti disponibili',
       'tasso di affollamento'],
      dtype='object')

In [15]:
# Adding institutes' information for mapping the institutes
# Read institutes' csv

df_info = pd.read_csv('../outputs/clean/institutes_info.csv')
df_info = df_info.rename(columns={'id_istituto': 'id istituto'})

merged_df = pd.merge(df_most_recent, df_info, on='id istituto')

# Adding additional columns
merged_df['posti disponibili'] = merged_df['posti regolamentari'] - merged_df['posti non disponibili']

merged_df['tasso di affollamento'] = round((merged_df['totale detenuti'] / merged_df['posti disponibili']) * 100, 0)


# Keep only relevant columns
df_filtered = merged_df[
  [
    'id istituto',
    'nome istituto',
    'tasso di affollamento',
    'indirizzo',
    'tipo istituto',
   'posti regolamentari',
    'posti non disponibili',
    'posti disponibili',
    'totale detenuti',
    'dati aggiornati al',
    'polizia penitenziaria - previsti',
    'polizia penitenziaria - effettivi',
    'personale polizia penitenziaria aggiornato al',
    'amministrativi - effettivi',
    'amministrativi - previsti',
    'personale amministrativo aggiornato al',
    'numero complessivo',
    'numero non disponibili',
    'doccia',
    'bidet',
    'portatori di handicap',
    'servizi igienici con porta',
    'accensione luce autonoma',
    'prese elettriche',
    'data di aggiornamento spazi detentivi',
    'latitudine',
    'longitude'
    ]
    ]

df_filtered.head(2)

,id istituto,nome istituto,tasso di affollamento,indirizzo,tipo istituto,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,dati aggiornati al,...,numero non disponibili,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,data di aggiornamento spazi detentivi,latitudine,longitude
0,MII152284,Genova Marassi,125.0,Piazzale Marassi n.2 - 16139 Genova,Casa circondariale,535.0,1.0,534.0,665.0,2026-05-27,...,1.0,128.0,175.0,3.0,213.0,100.0,0.0,2026-05-27,44.417913,8.951100
1,MII157783,Alba,86.0,Loc.Toppino - Via Vivaro n. 14 - 12051 Alba,Casa di reclusione - Giuseppe Montalto,138.0,89.0,49.0,42.0,2026-05-27,...,86.0,22.0,112.0,1.0,112.0,22.0,22.0,2026-05-27,44.691542,8.025636

In [16]:
df_filtered['scheda istituto'] = '<a href="https://www.giustizia.it/giustizia/page/it/dettaglio_scheda_istituto_penitenziario?s=' + df_filtered['id istituto'] + '">Vai alla scheda istituto</a>'


df_filtered.head()

/tmp/ipykernel_3877/3401019820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['scheda istituto'] = '<a href="https://www.giustizia.it/giustizia/page/it/dettaglio_scheda_istituto_penitenziario?s=' + df_filtered['id istituto'] + '">Vai alla scheda istituto</a>'

,id istituto,nome istituto,tasso di affollamento,indirizzo,tipo istituto,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,dati aggiornati al,...,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,data di aggiornamento spazi detentivi,latitudine,longitude,scheda istituto
0,MII152284,Genova Marassi,125.0,Piazzale Marassi n.2 - 16139 Genova,Casa circondariale,535.0,1.0,534.0,665.0,2026-05-27,...,128.0,175.0,3.0,213.0,100.0,0.0,2026-05-27,44.417913,8.951100,"<a href=""https://www.giustizia.it/giustizia/pa..."
1,MII157783,Alba,86.0,Loc.Toppino - Via Vivaro n. 14 - 12051 Alba,Casa di reclusione - Giuseppe Montalto,138.0,89.0,49.0,42.0,2026-05-27,...,22.0,112.0,1.0,112.0,22.0,22.0,2026-05-27,44.691542,8.025636,"<a href=""https://www.giustizia.it/giustizia/pa..."
2,MII158895,Milano San Vittore,209.0,Piazza Filangieri n.2 - 20123 Milano,Casa circondariale - Francesco Di Cataldo,702.0,218.0,484.0,1010.0,2026-05-27,...,272.0,184.0,0.0,327.0,325.0,325.0,2026-05-27,45.461598,9.166399,"<a href=""https://www.giustizia.it/giustizia/pa..."
3,MII158901,Belluno,130.0,Via Baldenich n.11 - 32100 Belluno,Casa circondariale,86.0,4.0,82.0,107.0,2026-05-27,...,24.0,24.0,0.0,48.0,44.0,44.0,2026-05-27,46.139738,12.219297,"<a href=""https://www.giustizia.it/giustizia/pa..."
4,MII158910,Agrigento,136.0,Piazza Di Lorenzo n. 1 - 92100 Agrigento,Casa circondariale - Pasquale Di Lorenzo,283.0,19.0,264.0,358.0,2026-05-27,...,192.0,42.0,0.0,247.0,228.0,0.0,2026-05-27,37.319422,13.617396,"<a href=""https://www.giustizia.it/giustizia/pa..."

In [17]:
# Create a copy first to avoid the warning
df_filtered = df_filtered.copy()

# Calculate metrics using loc for proper assignment
df_filtered.loc[:, 'stanze_disponibili'] = df_filtered['numero complessivo'] - df_filtered['numero non disponibili']

# Create list of columns to process
metrics = {
    'detenuti_stanza': lambda x: (x['totale detenuti'] / x['stanze_disponibili']).round(2),
    'polizia_pers': lambda x:  (x['polizia penitenziaria - effettivi']/ x['totale detenuti']).round(2),
    'doccia_pers': lambda x:  (x['totale detenuti'] / x['doccia']).round(2),
    'bidet_pers': lambda x:  (x['totale detenuti'] / x['bidet']).round(2),
    'servizi_pers': lambda x:  (x['totale detenuti'] / x['servizi igienici con porta']).round(2),
    'luci_pers': lambda x:  (x['totale detenuti'] / x['accensione luce autonoma']).round(2),
    'prese_pers': lambda x: (x['totale detenuti'] / x['prese elettriche']).round(2)
}

# Apply calculations
for col, func in metrics.items():
    df_filtered.loc[:, col] = func(df_filtered).replace([np.inf, -np.inf], np.nan)

In [18]:
df_filtered.sample(4)

,id istituto,nome istituto,tasso di affollamento,indirizzo,tipo istituto,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,dati aggiornati al,...,longitude,scheda istituto,stanze_disponibili,detenuti_stanza,polizia_pers,doccia_pers,bidet_pers,servizi_pers,luci_pers,prese_pers
43,MII173285,Catania Bicocca,129.0,Tangenziale Ovest km 8 n. s.n.c. - 95030 Catania,Casa circondariale,136.0,6.0,130.0,168.0,2026-05-27,...,14.944202,"<a href=""https://www.giustizia.it/giustizia/pa...",122.0,1.38,1.22,1.37,NaN,1.32,NaN,NaN
169,MII181661,Trieste,185.0,Via Coroneo n. 26/28 - 34133 Trieste,Casa circondariale - Ernesto Mari,150.0,15.0,135.0,250.0,2026-05-27,...,13.780733,"<a href=""https://www.giustizia.it/giustizia/pa...",49.0,5.10,0.49,50.00,6.41,5.21,35.71,3.91
120,MII179830,Pescara,163.0,Via San Donato n.2- 65129 Pescara,Casa circondariale,276.0,33.0,243.0,397.0,2026-05-27,...,14.215016,"<a href=""https://www.giustizia.it/giustizia/pa...",94.0,4.22,0.36,3.78,26.47,3.61,3.61,3.64
118,MII179781,Perugia,158.0,Strada Pievaiola n.252 - 06132 Perugia,Casa circondariale - Nuovo complesso penitenzi...,363.0,56.0,307.0,485.0,2026-05-27,...,12.262603,"<a href=""https://www.giustizia.it/giustizia/pa...",254.0,1.91,0.39,1.58,12.12,1.56,1.56,1.56

In [19]:
# Saving csv
df_filtered.to_csv('../outputs/viz/institutes_most_recent.csv', index=False, encoding='UTF-8-sig')

## 1. Totals

In [20]:
grouped_df = df.groupby('dati aggiornati al').sum(numeric_only=True).reset_index()
grouped_df

,dati aggiornati al,posti regolamentari,posti non disponibili,totale detenuti,polizia penitenziaria - effettivi,polizia penitenziaria - previsti,amministrativi - effettivi,amministrativi - previsti,educatori - effettivi,educatori - previsti,numero complessivo,numero non disponibili,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche
0,2024-10-05,51196.0,4384.0,61880.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-10-06,51196.0,4384.0,61912.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2024-10-07,51196.0,4441.0,61846.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2024-10-09,51195.0,4439.0,61863.0,31091.0,34035.0,3414.0,4079.0,978.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2024-10-10,51195.0,4437.0,61843.0,31091.0,34035.0,3414.0,4079.0,978.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,2026-05-21,51269.0,4970.0,64631.0,31314.0,34035.0,3606.0,4083.0,917.0,1002.0,31934.0,3209.0,14506.0,13774.0,445.0,30501.0,24656.0,21272.0
472,2026-05-22,51269.0,4969.0,64621.0,31314.0,34035.0,3606.0,4083.0,917.0,1002.0,31934.0,3209.0,14506.0,13774.0,445.0,30501.0,24656.0,21272.0
473,2026-05-23,51269.0,4965.0,64677.0,31314.0,34035.0,3606.0,4083.0,917.0,1002.0,31934.0,3205.0,14506.0,13774.0,445.0,30501.0,24656.0,21272.0
474,2026-05-24,51269.0,4965.0,64717.0,31314.0,34035.0,3606.0,4083.0,917.0,1002.0,31934.0,3205.0,14506.0,13774.0,445.0,30501.0,24656.0,21272.0
475,2026-05-27,51269.0,4963.0,64711.0,31236.0,37965.0,3423.0,4083.0,928.0,1002.0,31934.0,3204.0,14506.0,13774.0,445.0,30501.0,24656.0,21272.0

In [21]:
grouped_df['posti disponibili'] = (grouped_df['posti regolamentari'] - grouped_df['posti non disponibili']).round(0)
grouped_df['tasso di affollamento'] = (grouped_df['totale detenuti'] / grouped_df['posti disponibili'] * 100).round(4).astype(float)

grouped_df.head()

,dati aggiornati al,posti regolamentari,posti non disponibili,totale detenuti,polizia penitenziaria - effettivi,polizia penitenziaria - previsti,amministrativi - effettivi,amministrativi - previsti,educatori - effettivi,educatori - previsti,numero complessivo,numero non disponibili,doccia,bidet,portatori di handicap,servizi igienici con porta,accensione luce autonoma,prese elettriche,posti disponibili,tasso di affollamento
0,2024-10-05,51196.0,4384.0,61880.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46812.0,132.1883
1,2024-10-06,51196.0,4384.0,61912.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46812.0,132.2567
2,2024-10-07,51196.0,4441.0,61846.0,31433.0,34035.0,3388.0,4049.0,969.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46755.0,132.2768
3,2024-10-09,51195.0,4439.0,61863.0,31091.0,34035.0,3414.0,4079.0,978.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46756.0,132.3103
4,2024-10-10,51195.0,4437.0,61843.0,31091.0,34035.0,3414.0,4079.0,978.0,1001.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46758.0,132.2619

In [22]:
grouped_df = grouped_df[['dati aggiornati al', 'posti regolamentari', 'posti non disponibili', 'posti disponibili', 'totale detenuti', 'tasso di affollamento']]
# grouped_df['posti disponibili'] = grouped_df['posti regolamentari'] - grouped_df['posti non disponibili']
# grouped_df['tasso_affollamento'] = round((grouped_df['posti_occupati'] / grouped_df['posti_disponibili'])*100,4).astype(float)
grouped_df.head()

,dati aggiornati al,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,tasso di affollamento
0,2024-10-05,51196.0,4384.0,46812.0,61880.0,132.1883
1,2024-10-06,51196.0,4384.0,46812.0,61912.0,132.2567
2,2024-10-07,51196.0,4441.0,46755.0,61846.0,132.2768
3,2024-10-09,51195.0,4439.0,46756.0,61863.0,132.3103
4,2024-10-10,51195.0,4437.0,46758.0,61843.0,132.2619

In [23]:
grouped_df.tail(2)

,dati aggiornati al,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,tasso di affollamento
474,2026-05-24,51269.0,4965.0,46304.0,64717.0,139.7655
475,2026-05-27,51269.0,4963.0,46306.0,64711.0,139.7465

In [24]:
grouped_df.to_csv('../outputs/viz/institutes_totals.csv', index=False)

## Personale

In [25]:
df = pd.read_csv('../outputs/viz/institutes_most_recent.csv')
df.columns

Index(['id istituto', 'nome istituto', 'tasso di affollamento', 'indirizzo',
       'tipo istituto', 'posti regolamentari', 'posti non disponibili',
       'posti disponibili', 'totale detenuti', 'dati aggiornati al',
       'polizia penitenziaria - previsti', 'polizia penitenziaria - effettivi',
       'personale polizia penitenziaria aggiornato al',
       'amministrativi - effettivi', 'amministrativi - previsti',
       'personale amministrativo aggiornato al', 'numero complessivo',
       'numero non disponibili', 'doccia', 'bidet', 'portatori di handicap',
       'servizi igienici con porta', 'accensione luce autonoma',
       'prese elettriche', 'data di aggiornamento spazi detentivi',
       'latitudine', 'longitude', 'scheda istituto', 'stanze_disponibili',
       'detenuti_stanza', 'polizia_pers', 'doccia_pers', 'bidet_pers',
       'servizi_pers', 'luci_pers', 'prese_pers'],
      dtype='object')

In [26]:
df = pd.read_csv('../outputs/viz/institutes_most_recent.csv')


df_polizia = df[['nome istituto', 'totale detenuti', 'tasso di affollamento', 'polizia penitenziaria - previsti', 'polizia penitenziaria - effettivi', 'personale polizia penitenziaria aggiornato al', 'dati aggiornati al']]

df_polizia['polizia penitenziaria - mancante'] = df_polizia['polizia penitenziaria - previsti'] - df_polizia['polizia penitenziaria - effettivi']

df_polizia.head(2)

/tmp/ipykernel_3877/2362681573.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_polizia['polizia penitenziaria - mancante'] = df_polizia['polizia penitenziaria - previsti'] - df_polizia['polizia penitenziaria - effettivi']

,nome istituto,totale detenuti,tasso di affollamento,polizia penitenziaria - previsti,polizia penitenziaria - effettivi,personale polizia penitenziaria aggiornato al,dati aggiornati al,polizia penitenziaria - mancante
0,Genova Marassi,665.0,125.0,386.0,312.0,2026-04-30,2026-05-27,74.0
1,Alba,42.0,86.0,107.0,86.0,2026-04-30,2026-05-27,21.0

In [27]:
df_polizia['polizia penitenziaria - mancante percentuale'] = round(df_polizia['polizia penitenziaria - mancante'] / df_polizia['polizia penitenziaria - previsti']*100,2)
df_polizia.head(2)

/tmp/ipykernel_3877/989766878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_polizia['polizia penitenziaria - mancante percentuale'] = round(df_polizia['polizia penitenziaria - mancante'] / df_polizia['polizia penitenziaria - previsti']*100,2)

,nome istituto,totale detenuti,tasso di affollamento,polizia penitenziaria - previsti,polizia penitenziaria - effettivi,personale polizia penitenziaria aggiornato al,dati aggiornati al,polizia penitenziaria - mancante,polizia penitenziaria - mancante percentuale
0,Genova Marassi,665.0,125.0,386.0,312.0,2026-04-30,2026-05-27,74.0,19.17
1,Alba,42.0,86.0,107.0,86.0,2026-04-30,2026-05-27,21.0,19.63

In [28]:
df_polizia_clean = df_polizia[df_polizia['totale detenuti'] != 0]
df_polizia_clean.sort_values('polizia penitenziaria - mancante percentuale', ascending=False).head(2)

,nome istituto,totale detenuti,tasso di affollamento,polizia penitenziaria - previsti,polizia penitenziaria - effettivi,personale polizia penitenziaria aggiornato al,dati aggiornati al,polizia penitenziaria - mancante,polizia penitenziaria - mancante percentuale
2,Milano San Vittore,1010.0,209.0,858.0,562.0,2026-04-30,2026-05-27,296.0,34.50
95,Matera,203.0,166.0,149.0,98.0,2026-04-30,2026-05-27,51.0,34.23

In [29]:
critical_prisons = df_polizia_clean[(df_polizia_clean['tasso di affollamento'] > 120) & (df_polizia_clean['polizia penitenziaria - mancante percentuale'] > 20)].reset_index(drop=True)
critical_prisons

,nome istituto,totale detenuti,tasso di affollamento,polizia penitenziaria - previsti,polizia penitenziaria - effettivi,personale polizia penitenziaria aggiornato al,dati aggiornati al,polizia penitenziaria - mancante,polizia penitenziaria - mancante percentuale
0,Milano San Vittore,1010.0,209.0,858.0,562.0,2026-04-30,2026-05-27,296.0,34.50
1,Belluno,107.0,130.0,94.0,74.0,2026-04-30,2026-05-27,20.0,21.28
2,Busto Arsizio,444.0,205.0,217.0,166.0,2026-04-30,2026-05-27,51.0,23.50
3,Biella,566.0,144.0,229.0,180.0,2026-04-30,2026-05-27,49.0,21.40
4,Bologna,835.0,178.0,520.0,409.0,2026-04-30,2026-05-27,111.0,21.35
5,Bolzano,113.0,130.0,84.0,64.0,2026-04-30,2026-05-27,20.0,23.81
6,Cagliari Uta,735.0,131.0,438.0,324.0,2026-04-30,2026-05-27,114.0,26.03
7,Campobasso,180.0,178.0,112.0,86.0,2026-04-30,2026-05-27,26.0,23.21
8,Cassino,156.0,175.0,142.0,109.0,2026-04-30,2026-05-27,33.0,23.24
9,Catania Bicocca,168.0,129.0,276.0,205.0,2026-04-30,2026-05-27,71.0,25.72
10,Crotone,83.0,132.0,85.0,64.0,2026-04-30,2026-05-27,21.0,24.71
11,Cremona,613.0,160.0,223.0,170.0,2026-04-30,2026-05-27,53.0,23.77
12,Fermo,79.0,184.0,56.0,44.0,2026-04-30,2026-05-27,12.0,21.43
13,Ferrara,406.0,167.0,216.0,158.0,2026-04-30,2026-05-27,58.0,26.85
14,Frosinone,677.0,134.0,326.0,258.0,2026-04-30,2026-05-27,68.0,20.86
15,Livorno,227.0,152.0,301.0,238.0,2026-04-30,2026-05-27,63.0,20.93
16,Massa,292.0,167.0,140.0,110.0,2026-04-30,2026-05-27,30.0,21.43
17,Matera,203.0,166.0,149.0,98.0,2026-04-30,2026-05-27,51.0,34.23
18,Melfi,107.0,160.0,163.0,123.0,2026-04-30,2026-05-27,40.0,24.54
19,Padova Nuovo Complesso,661.0,153.0,392.0,300.0,2026-04-30,2026-05-27,92.0,23.47
20,Parma,806.0,124.0,483.0,352.0,2026-04-30,2026-05-27,131.0,27.12
21,Perugia,485.0,158.0,251.0,189.0,2026-04-30,2026-05-27,62.0,24.70
22,Porto Azzurro,408.0,122.0,205.0,150.0,2026-04-30,2026-05-27,55.0,26.83
23,Ravenna,78.0,159.0,83.0,65.0,2026-04-30,2026-05-27,18.0,21.69
24,Roma Rebibbia Nuovo Complesso,1622.0,152.0,939.0,735.0,2026-04-30,2026-05-27,204.0,21.73
25,Roma Regina Coeli,991.0,173.0,480.0,363.0,2026-04-30,2026-05-27,117.0,24.38
26,Rovigo,273.0,131.0,185.0,140.0,2026-04-30,2026-05-27,45.0,24.32
27,Sassari,581.0,127.0,384.0,290.0,2026-04-30,2026-05-27,94.0,24.48
28,Teramo,463.0,184.0,221.0,174.0,2026-04-30,2026-05-27,47.0,21.27
29,Torino,1508.0,138.0,901.0,691.0,2026-04-30,2026-05-27,210.0,23.31
30,Trani,449.0,151.0,266.0,209.0,2026-04-30,2026-05-27,57.0,21.43
31,Treviso,224.0,170.0,159.0,127.0,2026-04-30,2026-05-27,32.0,20.13
32,Trieste,250.0,185.0,160.0,123.0,2026-04-30,2026-05-27,37.0,23.12
33,Udine,161.0,187.0,122.0,88.0,2026-04-30,2026-05-27,34.0,27.87
34,Velletri,585.0,152.0,296.0,225.0,2026-04-30,2026-05-27,71.0,23.99
35,Vercelli,370.0,168.0,204.0,161.0,2026-04-30,2026-05-27,43.0,21.08
36,Viterbo,664.0,168.0,350.0,279.0,2026-04-30,2026-05-27,71.0,20.29
37,Reggio Emilia,308.0,132.0,236.0,187.0,2026-04-30,2026-05-27,49.0,20.76
38,Pisa,288.0,156.0,219.0,175.0,2026-04-30,2026-05-27,44.0,20.09

In [30]:
critical_prisons.to_csv('../outputs/viz/institutes_critical.csv', index=False, encoding='UTF-8-sig')

### Tasso Reale

In [31]:
df1 = pd.read_csv('../outputs/viz/bulletines_totals.csv')
df2 = pd.read_csv('../outputs/viz/institutes_totals.csv')

In [32]:
df2.tail(2)

,dati aggiornati al,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,tasso di affollamento
474,2026-05-24,51269.0,4965.0,46304.0,64717.0,139.7655
475,2026-05-27,51269.0,4963.0,46306.0,64711.0,139.7465

In [33]:
# Renaming columns for clarity and merging on a unified date column
df1.rename(columns={'Ultimo aggiornamento': 'Date', 'tasso_affollamento': 'tasso_affollamento_ufficiale'}, inplace=True)
df2.rename(columns={'dati aggiornati al': 'Date', 'tasso di affollamento': 'tasso_affollamento_reale'}, inplace=True)

In [34]:
# Converting the Date columns to datetime for consistency
df1['Date'] = pd.to_datetime(df1['Date'])
df2['Date'] = pd.to_datetime(df2['Date'])

In [35]:
df2.tail(2)

,Date,posti regolamentari,posti non disponibili,posti disponibili,totale detenuti,tasso_affollamento_reale
474,2026-05-24,51269.0,4965.0,46304.0,64717.0,139.7655
475,2026-05-27,51269.0,4963.0,46306.0,64711.0,139.7465

In [36]:
merged_df = pd.merge(df1[['Date', 'tasso_affollamento_ufficiale']], 
                     df2[['Date', 'tasso_affollamento_reale']], 
                     on='Date', 
                     how='outer')
merged_df.sort_values(by='Date', inplace=True)

merged_df.tail(2)

          Date  tasso_affollamento_ufficiale  tasso_affollamento_reale
544 2026-05-24                           NaN                  139.7655
545 2026-05-27                           NaN                  139.7465

In [37]:
filtered_df = merged_df[merged_df['Date'] > '2024-08-01']
filtered_df.tail(2)

          Date  tasso_affollamento_ufficiale  tasso_affollamento_reale
544 2026-05-24                           NaN                  139.7655
545 2026-05-27                           NaN                  139.7465

In [38]:
# Apply linear interpolation for missing values
filtered_df['tasso_affollamento_ufficiale (interpolated)'] = round((filtered_df['tasso_affollamento_ufficiale'].interpolate(method='linear')),4)
filtered_df['tasso_affollamento_reale (interpolated)'] = round((filtered_df['tasso_affollamento_reale'].interpolate(method='linear')),4)

filtered_df.tail(2)

/tmp/ipykernel_3877/3090938612.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['tasso_affollamento_ufficiale (interpolated)'] = round((filtered_df['tasso_affollamento_ufficiale'].interpolate(method='linear')),4)
/tmp/ipykernel_3877/3090938612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['tasso_affollamento_reale (interpolated)'] = round((filtered_df['tasso_affollamento_reale'].interpolate(method='linear')),4)

,Date,tasso_affollamento_ufficiale,tasso_affollamento_reale,tasso_affollamento_ufficiale (interpolated),tasso_affollamento_reale (interpolated)
544,2026-05-24,NaN,139.7655,120.694,139.7655
545,2026-05-27,NaN,139.7465,120.694,139.7465

In [39]:
filtered_df.to_csv('../outputs/viz/tasso_affollamento.csv', index=False)

In [40]:
df_reale = filtered_df[['Date', 'tasso_affollamento_reale']]
df_reale = df_reale[df_reale['tasso_affollamento_reale'].notna()]
df_reale.head(2)

         Date  tasso_affollamento_reale
69 2024-10-05                  132.1883
70 2024-10-06                  132.2567

In [41]:
df_reale.to_csv('../outputs/viz/tasso_reale.csv', index=False)